---
- hosts: all
  become: yes
  tasks:
    - name: Checking os version.......
      debug:
        msg: "The os family is {{ansible_os_family}}"
    - name: Installing apache2.......
      apt:
        name: apache2
        state: latest
    - name: Staring service........    
      service:
        name: apache2
        state: started   
     
