---
- hosts: all
  become: yes
  vars:
    fruits:
      - apple
      - orange
      - banana
  tasks:
    - name: listing fruits
      debug:
        msg: "The fruits are {{item}}"
      when: ansible_os_family == 'Redhat'
      loop: "{{fruits}}"  


                  

