---
- hosts: all
  become: true
  tasks:
    - name: creating multiple users     
      user:
        name: "{{item}}" 
        state: present
      loop:
        - dhawan
        - iyer
        - yadav       

