---
- hosts: all
  become: yes 
  gather_facts: yes
  tasks:
    - name: Checking os name..........
      debug:
        msg: "The os name is {{ansible_os_family}}"
    - name: Installing apache2..........
      apt:
        name: apache2
        state: present
   # when: ansible_os_family == "Redhat" 
    - name: Starting apache2..........
      service:
        name: apache2
        state: started
 

